#!/bin/bash
#SBATCH -J Pipe_CAN
#SBATCH -N 1
#SBATCH -p cnall
#SBATCH -o stdout.Pipe
#SBATCH -e stderr.Pipe
#SBATCH --no-requeue
#SBATCH --ntasks-per-node=56 #根据实际情况设置

source /home/tongdan/anaconda3/etc/profile.d/conda.sh
conda activate ccus

date
cd /WORK/tongdan_work/yanxizhe/CCS/Global_turnover_240624/DPEC_GID/4_SSM/PreNet/PreNet_Canada+Latin-America/scr
python S1_ISOPointConn.py >log1
python S2_NetBuild.py >log2
python S3_NodesName.py >log3
python S4_EdgeGet.py >log4
python S5_NetworkDone.py >log5
python S6_NetworkRead.py >log6

date
printf "Scenario finish"